image: golang:1.8-alpine

cache:
  paths:
    - .glide
    - vendor/

before_script:
- apk add --no-cache git curl
- curl -s https://glide.sh/get | sh
- go-wrapper download
- glide install

stages:
- build
- release

test:
    stage: build
    script:
    - cd /go/src/github.com/iprods/golodns
    - go test $(go list ./... | grep -v '/vendor/') -v

build-linux:
    stage: build
    script:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
    artifacts:
        name: "golodns_$CI_JOB_ID"
        paths:
        - golodns
        when: on_success

build-macos:
    stage: build
    script:
    - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build
    artifacts:
        name: "golodns_$CI_JOB_ID"
        paths:
        - golodns
        when: on_success

release-macos:
    stage: release
    script:
    - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-w"
    artifacts:
        name: "golodns"
        paths:
        - golodns
        when: on_success
    only:
    - tags

release-linux:
    stage: release
    script:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-w"
    artifacts:
        name: "golodns"
        paths:
        - golodns
        when: on_success
    only:
    - tags
